# Generated by Django 5.1.1 on 2024-12-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
