# Generated by Django 5.1.1 on 2024-12-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_sermon_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='preacher_profile_pic',
        ),
        migrations.AddField(
            model_name='sermon',
            name='preacher_profile_pic_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='video_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
